name: Publish NuGet@cardboard-box
author: Cardboard - Alireza Sabouri (@alirezanet) - ford Rohith Reddy (@rohith)
description: Build, Pack & Publish a NuGet package with dotnet core on project version change (forked from alirezanet/publish-nuget)

inputs:
    PROJECT_FILE_PATH:
        description: Filepath of the project to be packaged, relative to root of repository
        required: true
    PACKAGE_NAME:
        description: NuGet package id, used for version detection & defaults to project name
        required: false
    VERSION_FILE_PATH:
        description: Filepath with version info, relative to root of repository & defaults to PROJECT_FILE_PATH
        required: false
    VERSION_REGEX:
        description: Regex pattern to extract version info in a capturing group
        required: false
        default: ^\s*<Version>(.*)<\/Version>\s*$
    VERSION_STATIC:
        description: Useful with external providers like Nerdbank.GitVersioning, ignores VERSION_FILE_PATH & VERSION_REGEX
        required: false
    TAG_COMMIT:
        description: Flag to toggle git tagging, enabled by default
        required: false
        default: true
    TAG_FORMAT:
        description: Format of the git tag, [*] gets replaced with actual version
        required: false
        default: v*
    NUGET_KEY:
        description: API key to authenticate with NuGet server
        required: false
    NUGET_SOURCE:
        description: NuGet server uri hosting the packages, defaults to https://api.nuget.org
        required: false
        default: https://api.nuget.org
    INCLUDE_SYMBOLS:
        description: Flag to toggle pushing symbols along with nuget package to the server, disabled by default
        required: false
        default: false
    NO_BUILD:
        description: Flag to toggle not building the project and letting pack command handle restoring & building, disabled by default
        required: false
        default: false
    USE_GITHUB_NUGET_REGISTRY:
        description: Flag to toggle using GitHub's NuGet registry, disabled by default - This overwrites NUGET_SOURCE
        required: false
        default: false
    GITHUB_NUGET_NAMESPACE:
        description: Namespace for the GitHub NuGet registry, defaults to the repository owner's name
        required: false
    GITHUB_NUGET_USERNAME:
        description: Username for the GitHub NuGet registry, defaults to the repository owner's name
        required: false
    GITHUB_NUGET_TOKEN:
        description: Personal access token for the GitHub NuGet registry, defaults to GITHUB_TOKEN
        required: false

outputs:
    VERSION:
        description: Version of the associated git tag

    PACKAGE_NAME:
        description: Name of the NuGet package generated
    
    PACKAGE_PATH:
        description: Path to the generated NuGet package

    SYMBOLS_PACKAGE_NAME:
        description: Name of the symbols package generated
    
    SYMBOLS_PACKAGE_PATH:
        description: Path to the generated symbols package

runs:
    using: node16
    main: index.js

branding:
    icon: package
    color: blue
